# Generated by Django 2.2.9 on 2020-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201209_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
