# Generated by Django 2.2.9 on 2020-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201212_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
