# Generated by Django 2.2.9 on 2020-12-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Solomon Grandy', max_length=1000),
            preserve_default=False,
        ),
    ]
