# Generated by Django 3.0.8 on 2020-10-02 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('comedy', 'comedy'), ('humanity', 'Humanity'), ('music', 'Music'), ('poetry', 'Poetry'), ('fitness', 'Fitness'), ('auto', 'Auto/Moto'), ('travel', 'Travel'), ('food', 'Food'), ('sports', 'Sports'), ('spiritual', 'Spiritual'), ('photography', 'Photography'), ('fashion', 'Fashion'), ('dance', 'Dance'), ('acting', 'Acting'), ('architectures', 'Architectures'), ('education', 'Education'), ('cricket', 'Cricket'), ('art', 'Art')], default='select option', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='main.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
