# Generated by Django 3.0.8 on 2020-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('food', 'Food'), ('music', 'Music'), ('art', 'Art'), ('photography', 'Photography'), ('spiritual', 'Spiritual'), ('comedy', 'comedy'), ('sports', 'Sports'), ('auto', 'Auto/Moto'), ('fashion', 'Fashion'), ('acting', 'Acting'), ('poetry', 'Poetry'), ('cricket', 'Cricket'), ('dance', 'Dance'), ('humanity', 'Humanity'), ('architectures', 'Architectures'), ('travel', 'Travel'), ('education', 'Education')], default='select option', max_length=20),
        ),
    ]
