# Generated by Django 3.0.8 on 2020-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201002_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('sports', 'Sports'), ('art', 'Art'), ('fitness', 'Fitness'), ('dance', 'Dance'), ('cricket', 'Cricket'), ('fashion', 'Fashion'), ('music', 'Music'), ('acting', 'Acting'), ('education', 'Education'), ('spiritual', 'Spiritual'), ('auto', 'Auto/Moto'), ('poetry', 'Poetry'), ('comedy', 'comedy'), ('photography', 'Photography'), ('humanity', 'Humanity'), ('architectures', 'Architectures'), ('food', 'Food')], default='select option', max_length=20),
        ),
    ]
