# Generated by Django 3.0.8 on 2020-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('plus', 'Like'), ('user-plus', 'Follow')], max_length=10),
        ),
    ]
