# Generated by Django 3.0.8 on 2020-10-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201002_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('comedy', 'comedy'), ('acting', 'Acting'), ('fitness', 'Fitness'), ('cricket', 'Cricket'), ('food', 'Food'), ('poetry', 'Poetry'), ('architectures', 'Architectures'), ('music', 'Music'), ('auto', 'Auto/Moto'), ('photography', 'Photography'), ('education', 'Education'), ('humanity', 'Humanity'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('dance', 'Dance'), ('travel', 'Travel'), ('spiritual', 'Spiritual')], default='select option', max_length=20),
        ),
    ]
