# Generated by Django 2.2.9 on 2020-12-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201011_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('photography', 'Photography'), ('design', 'Design')], default='art', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.BooleanField(default=False),
        ),
    ]
