# Generated by Django 3.0.8 on 2020-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201005_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('sports', 'Sports'), ('cricket', 'Cricket'), ('dance', 'Dance'), ('humanity', 'Humanity'), ('food', 'Food'), ('travel', 'Travel'), ('comedy', 'comedy'), ('music', 'Music'), ('spiritual', 'Spiritual'), ('auto', 'Auto/Moto'), ('fashion', 'Fashion'), ('fitness', 'Fitness'), ('art', 'Art'), ('architectures', 'Architectures'), ('photography', 'Photography'), ('acting', 'Acting'), ('poetry', 'Poetry')], default='select option', max_length=20),
        ),
    ]
