# Generated by Django 3.0.8 on 2020-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201005_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('architectures', 'Architectures'), ('education', 'Education'), ('cricket', 'Cricket'), ('poetry', 'Poetry'), ('auto', 'Auto/Moto'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('art', 'Art'), ('travel', 'Travel'), ('dance', 'Dance'), ('humanity', 'Humanity'), ('food', 'Food'), ('spiritual', 'Spiritual'), ('acting', 'Acting'), ('photography', 'Photography'), ('fitness', 'Fitness'), ('music', 'Music'), ('comedy', 'comedy')], default='select option', max_length=20),
        ),
    ]
