# Generated by Django 3.0.8 on 2020-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201005_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('travel', 'Travel'), ('auto', 'Auto/Moto'), ('spiritual', 'Spiritual'), ('music', 'Music'), ('dance', 'Dance'), ('acting', 'Acting'), ('humanity', 'Humanity'), ('art', 'Art'), ('food', 'Food'), ('cricket', 'Cricket'), ('comedy', 'comedy'), ('architectures', 'Architectures'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('poetry', 'Poetry'), ('education', 'Education'), ('fitness', 'Fitness')], default='select option', max_length=20),
        ),
    ]
