# Generated by Django 3.0.8 on 2020-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201005_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('acting', 'Acting'), ('cricket', 'Cricket'), ('art', 'Art'), ('humanity', 'Humanity'), ('spiritual', 'Spiritual'), ('auto', 'Auto/Moto'), ('music', 'Music'), ('food', 'Food'), ('travel', 'Travel'), ('dance', 'Dance'), ('poetry', 'Poetry'), ('comedy', 'comedy'), ('architectures', 'Architectures'), ('fashion', 'Fashion'), ('photography', 'Photography'), ('sports', 'Sports'), ('fitness', 'Fitness')], default='select option', max_length=20),
        ),
    ]
