# Generated by Django 2.2.9 on 2020-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('photography', 'Photography')], default='art', max_length=20),
        ),
    ]
