# Generated by Django 2.2.9 on 2020-12-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reason',
            field=models.CharField(choices=[('buy', 'Buy'), ('customize_work', 'Customize Work'), ('booking', 'Booking'), ('exhibition', 'Exhibition'), ('event', 'Event')], default='buy', max_length=50),
            preserve_default=False,
        ),
    ]
