# Generated by Django 2.2.9 on 2020-12-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_inquiry_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='post',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
            preserve_default=False,
        ),
    ]
