# Generated by Django 2.2.9 on 2021-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201231_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('bug_report', 'Bug Report'), ('improvement', 'Improvement')], max_length=50),
        ),
    ]
